feat : Added few Cybersecurity related Quiz questions
freeCodeCamp/Developer_Quiz_Site pull request #105
Opened 2022-09-16 22:47 UTC by Jayaram18

In reference to the article below,
https://www.freecodecamp.org/news/white-hat-black-hat-red-hat-hackers/ , I've added 2 questions with respect to Black Hat and White Hat Hackers.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #104

2022-09-17 02:40 UTC, jdwilkin4 commented
Hi @Jayaram18 ! 

I removed the link that closes the PR.
Please make sure to read the issues very carefully because some of them are not supposed to be closed because we want multiple people to contribute to them. 
Thanks for understanding! 👍

2022-09-17 02:51 UTC, jdwilkin4 requested changes
HI @Jayaram18 ! 

Thank you for your quiz questions! 
Once you fix the following issues, then it will be ready to merge. 👍

2022-09-17 02:51 UTC, jdwilkin4 commented on src/data/full-quiz.ts
> +      "White Hat Hackers work for organizations as Cybersecurity Engineers, Penetration Tester, Security Analyst, CISO etc where they perform tasks like scanning the network, configuring Intrution De
I think we should cut this sentence down because it will probably look a little long when it is in the answer modal.  
If the user wants to learn more, they can click on the learn more link in the answer more which will provide more detailed explanations. 

```suggestion
      "White Hat Hackers work for organizations as Cybersecurity Engineers, Penetration Testers, etc.  where they perform tasks like ethically hacking the system to find and report vulnerabilities. ",
```

2022-09-17 02:51 UTC, jdwilkin4 commented on src/data/full-quiz.ts
> +      "Which of the following type of Hackers protect civilians and organizations by finding and reporting vulnerabilites in the system?",
It looks like we have a spelling error for vulnerabilities. 

```suggestion
      "Which of the following types of Hackers protect civilians and organizations by finding and reporting vulnerabilities in the system?",
```

2022-09-17 04:35 UTC, jdwilkin4 approved these changes
We look forward to future contributions! 👍

2022-09-17 04:35 UTC, merged

2022-10-04 06:59 UTC, suryakapurothu commented
Wow, this thread looks great 
Can you @Jayaram18 help me make a few more question contributions?