Added Two CS related quiz
freeCodeCamp/Developer_Quiz_Site pull request #109
Opened 2022-09-20 17:21 UTC by Aman0786-git

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-09-20 17:23 UTC, Aman0786-git commented
This is my first contribution in an Open Source project . Please guide me if had made any mistake.Thankyou

2022-09-20 19:08 UTC, jdwilkin4 requested changes
Hi @Aman0786-git ! 
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-09-20 19:08 UTC, jdwilkin4 commented on src/data/full-quiz.ts
> +    Explanation: "Big O (O()) - Upper Bound ,Omega (Ω()) - Lower Bound , Theta (Θ()) - exact bound & Little O (o()) - describes the upper bound excluding the exact bound of the complexity ",
The explanation can be cleaned up a little bit. Let's just show the explanation for Little O. If they want to read more then they can click on the link for the article. 

```suggestion
    Explanation: "Little O (o()) describes the upper bound excluding the exact bound of the complexity ",
```

2022-09-20 19:08 UTC, jdwilkin4 commented on src/data/full-quiz.ts
> +    Explanation: "O(1) often called as constant time is best for algorithms\nO(log(n)) is less complex than O(√n), because the square root function can be considered a polynomial, where the exponent
The following explanation is a little long and would make the answer modal to crowded. Let's cut it down to just say all of the answers are correct. If the user wants to learn more, then they can click on the corresponding article. 

```suggestion
    Explanation: "All of the above options about Big O are correct. ",
```

2022-09-21 04:36 UTC, Aman0786-git commented
@jdwilkin4 Thanks for the review , I will make the changes .

2022-09-21 15:16 UTC, merged

2022-09-21 17:15 UTC, Aman0786-git commented
@jdwilkin4 Thankyou will try to contribute regularly. :-)