Added some questions to security-quiz.ts related to cloud computing secutity
freeCodeCamp/Developer_Quiz_Site pull request #1170
Opened 2024-10-18 14:24 UTC by tsr94

## Summary of changes

Added a set of security-related multiple-choice questions to the security-quiz.ts file. The questions are from cloud cyber security.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [ x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [ x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x ] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x ] I have provided a summary of my changes.

closes #1135

2024-10-21 10:44 UTC, ilenia-magoni commented
Please do not close the issue, as per written in the issue. Instead write "Related to"

2024-10-21 15:27 UTC, jdwilkin4 requested changes
A few grammar and punctuation fixes but otherwise looks good

2024-10-21 15:27 UTC, jdwilkin4 commented on src/data/security-quiz.ts
> +      "Which of the following is an example of a denial-of-service (DoS) attack??",
```suggestion
      "Which of the following is an example of a denial-of-service (DoS) attack?",
```

2024-10-21 15:27 UTC, jdwilkin4 commented on src/data/security-quiz.ts
> +      "ISO/IEC 27001 is an internationally recognized standard for information security, including cloud environments",
```suggestion
      "ISO/IEC 27001 is an internationally recognized standard for information security, including cloud environments.",
```

2024-10-21 18:25 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2024-10-21 18:25 UTC, merged

2024-10-22 04:10 UTC, tsr94 commented
Thank you [jdwilkin4](https://github.com/jdwilkin4), Very happy