Javascript Question Added
freeCodeCamp/Developer_Quiz_Site pull request #136
Opened 2022-10-01 17:59 UTC by shubhankar-shandilya-india

I have added a Javascript Question related to the scope used in javascript.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #14 

I have added a question on the scope used in Javascript.
I have written its explanation and linked an freeCodeCamp article

2022-10-01 20:41 UTC, jdwilkin4 commented
Please make sure not to add `Closes #14 ` to your PR's because that issue is supposed to stay open for multiple contributors.

2022-10-01 20:56 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-01 20:56 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "Which of the following scoping type does JavaScript use?",
```suggestion
      "Which of the following scoping types does JavaScript use?",
```

2022-10-01 21:26 UTC, shubhankar-shandilya-india commented
I have made the required changes.

2022-10-01 21:30 UTC, shubhankar-shandilya-india commented
If all changes done please approve and merge my Pull request.
Thankyou.

2022-10-01 21:49 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-01 21:49 UTC, merged

2022-10-08 18:59 UTC, jdwilkin4 commented
After further review, it looks like this question has come from this quiz site
https://www.sanfoundry.com/javascript-mcqs-closures/

As such, we are removing this question from our site because we don't endorse plagiarism.