Added two new questions for python quiz
freeCodeCamp/Developer_Quiz_Site pull request #163
Opened 2022-10-02 18:59 UTC by Kunal-Garg-12

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-02 23:57 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-02 23:57 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Link: "https://www.freecodecamp.org/news/python-pop-how-to-pop-from-a-list-or-an-array-in-python/#howtousethepopmethodwithnoparameteranamenoparametera",
We already have a question on the pop method for this Python quiz.
Please remove this duplicate question.

2022-10-02 23:57 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "Here we use the negative index to start slicing 4th index from the end of the string.",
```suggestion
      "Here we use the negative index to start slicing at the 4th index from the end of the string.",
```

2022-10-03 06:11 UTC, Kunal-Garg-12 commented
Edited as required. Please verify

2022-10-03 06:11 UTC, Kunal-Garg-12 commented
Edited as required. Please verify

2022-10-03 11:24 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-03 11:25 UTC, merged