fix(general-cs-quiz.ts) : added new question
freeCodeCamp/Developer_Quiz_Site pull request #172
Opened 2022-10-03 09:38 UTC by Chirag8023

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-03 12:20 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-03 12:20 UTC, jdwilkin4 commented on src/data/general-cs-quiz.ts
> +    Explanation: "a nibble is group of four bits or it's half of a byte.",
```suggestion
    Explanation: "A Nibble is a group of four bits (half of a byte).",
```

2022-10-05 06:14 UTC, Chirag8023 commented
Done changes
👍🏻

2022-10-05 11:22 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-05 11:23 UTC, merged