New branch1
freeCodeCamp/Developer_Quiz_Site pull request #178
Opened 2022-10-03 13:51 UTC by Moksh45

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-03 20:06 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-03 20:06 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +    Link: "https://dev.mysql.com/doc/refman/5.6/en/revoke.html#:~:text=The%20REVOKE%20statement%20enables%20system,1.4%2C%20%E2%80%9CGRANT%20Statement%E2%80%9D."
```suggestion
    Link: "https://dev.mysql.com/doc/refman/5.6/en/revoke.html"
```

2022-10-03 20:06 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +      "In SQL If You Want To Undo a GRANT, you Should use",
```suggestion
      "In SQL, what statement should you use to undo a GRANT statement?",
```

2022-10-04 06:47 UTC, Moksh45 commented on src/data/sql-quiz.ts
> +      "In SQL If You Want To Undo a GRANT, you Should use",
Ok, I am trying to solve this issue

2022-10-04 13:09 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-04 13:10 UTC, merged