Javascript quize - added two new questions
freeCodeCamp/Developer_Quiz_Site pull request #193
Opened 2022-10-04 08:05 UTC by isurumaldeniya

Checklist:

- [ x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #14

2022-10-04 13:37 UTC, jdwilkin4 commented
Please make sure not to include the `Closes #14 ` because this issue is supposed to stay open for multiple contributors.

2022-10-04 13:44 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-04 13:44 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Explanation: "JavaScript has three kinds of variable declarations. var declare a variable, optionally initializing it to a value, let declare a block scoped, local variable,optionally initializin
Let's trim down this quiz question a bit. If users want to learn more they can click on the learn more link to read the article. 

```suggestion
    Explanation: "JavaScript has three kinds of variable declarations: var, let and const.",
```

2022-10-04 13:44 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Question: "In JavaScript, from following what isn't use to declare a variable?",
```suggestion
    Question: "In JavaScript, which of the following is NOT the correct way to declare a variable?",
```

2022-10-04 13:44 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Explanation: "JavaScript has 7 primitive data types. Boolean, null, undefined, Number, BigInt, String, Symbol",
```suggestion
    Explanation: "JavaScript has 7 primitive data types. Boolean, null, undefined, Number, BigInt, String, and Symbol",
```

2022-10-04 18:28 UTC, isurumaldeniya commented
@jdwilkin4 Hi I have done the changes please review the code and let me know if anything needed to be changed.

2022-10-05 00:55 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-05 00:55 UTC, merged

2022-10-05 04:54 UTC, isurumaldeniya commented
@jdwilkin4 Thank you for the guidance throughout the PR. I really hope to contribute more to the freeCodeCamp in the future. 😄