Javascript question about data type
freeCodeCamp/Developer_Quiz_Site pull request #241
Opened 2022-10-08 13:37 UTC by ddoyediran

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-08 13:38 UTC, ddoyediran commented
@jdwilkin4 please, let me know if there is anything you want me to remove or add. Thank you

2022-10-08 18:27 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-08 18:27 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "Primitive and Reference types are the two basic groups of data types in Javascript.",
```suggestion
      "Primitive and Reference types are the two basic groups of data types in JavaScript.",
```

2022-10-08 18:52 UTC, ddoyediran commented
Done. Thank you

2022-10-09 02:40 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-09 02:41 UTC, merged