Add more python questions
freeCodeCamp/Developer_Quiz_Site pull request #245
Opened 2022-10-08 19:05 UTC by Mannuel25

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

2022-10-09 03:01 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-09 03:01 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Question: "Which of the following is not a tuple method?",
```suggestion
    Question: "In Python, which of the following is not a tuple method?",
```

2022-10-09 03:01 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Question: "What will be the data type of 'John Doe'.split()?",
```suggestion
    Question: "In Python, what will be the data type of 'John Doe'.split()?",
```

2022-10-09 03:01 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Question: "If my_nums = [8,9,10], which of the following can't be used to reverse the list?",
```suggestion
    Question: "In Python, if my_nums = [8,9,10], which of the following can't be used to reverse the list?",
```

2022-10-09 03:01 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Question: "Which built-in function returns all properties and methods of the specified object, without the values?",
```suggestion
    Question: "In Python, which built-in function returns all properties and methods of the specified object, without the values?",
```

2022-10-09 06:04 UTC, Mannuel25 commented
Thanks for the corrections, I'll do well to fix them all.

2022-10-10 22:47 UTC, Mannuel25 commented
Hi @jdwilkin4 , I've made the necessary corrections.

2022-10-11 02:00 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

Also, in the future, it is best to create a branch for new changes.
Please read through the contributing docs on how to do that.

2022-10-11 02:01 UTC, merged