Add qa question about a11y tools
freeCodeCamp/Developer_Quiz_Site pull request #259
Opened 2022-10-09 08:46 UTC by YuriDevAT

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-09 17:02 UTC, jdwilkin4 commented
If this category is approved, then this question will need to be moved to the accessibility quiz not the QA one.

2022-10-09 17:03 UTC, YuriDevAT commented
Yep, got it 👍🏽  Thanks!

2022-10-14 04:30 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-14 04:30 UTC, jdwilkin4 commented on src/data/quality-assurance-quiz.ts
> +      "Web accessibility evaluation tools are software programs or online services that help determine if web content meets accessibility standards.",
```suggestion
      "Web accessibility evaluation tools are programs used to ensure that software adheres to accessibility guidelines as laid out by the W3C.",
```

2022-10-14 04:30 UTC, jdwilkin4 commented on src/data/quality-assurance-quiz.ts
> +  },
This question looks good to me.
Quincy approved the new accessibility category.
I just pushed up a change to add that new category.

Please move this question over to the accessibility quiz. 👍

2022-10-14 20:11 UTC, jdwilkin4 commented
I am closing this PR because it looks like you opened up a new one

2022-10-14 20:11 UTC, closed without merging

2022-10-15 06:39 UTC, YuriDevAT commented
Thanks @jdwilkin4.