Added 1 Javascript Question
freeCodeCamp/Developer_Quiz_Site pull request #261
Opened 2022-10-09 08:50 UTC by P766-spec

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-09 08:51 UTC, P766-spec commented
Added 1 javascript Question related to in operator

2022-10-09 14:48 UTC, P766-spec commented
Added 1 sql question related to super key

2022-10-09 14:53 UTC, P766-spec commented
Hello @jdwilkin4 please checkout the added questions on js and sql!  Would love to contribute on more, Thank You.

2022-10-09 17:11 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-09 17:11 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "What keyword is used to check whether a given property is valid or not?",
```suggestion
      "In JavaScript, what keyword is used to check whether a given property in an object is valid?",
```

2022-10-09 17:11 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "The in keyword is used to check whether the given property is valid or not in Javascript.",
```suggestion
      "The in keyword is used to check whether the given property in an object is valid or not.",
```

2022-10-09 17:11 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +
please remove this extra space here

2022-10-09 17:11 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +    Question: "Which of the following allows you to uniquely identify a tuple?",
```suggestion
    Question: "In relational databases, which of the following allows you to uniquely identify a tuple?",
```

2022-10-09 18:14 UTC, P766-spec commented
Okkk!!!

On Sun, 9 Oct 2022, 22:41 Jessica Wilkins, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thank you for your contribution!
>
> Please review the requested changes.
> Once those changes have been implemented, then we can merge your PR into
> main. 👍
> ------------------------------
>
> In src/data/javascript-quiz.ts
> <https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/261#discussion_r990813446>
> :
>
> > @@ -1,4 +1,15 @@
>
>  const javascriptQuiz = [
>
> +  {
>
> +    Question:
>
> +      "What keyword is used to check whether a given property is valid or not?",
>
>
> ⬇️ Suggested change
>
> -      "What keyword is used to check whether a given property is valid or not?",
>
> +      "In JavaScript, what keyword is used to check whether a given property in an object is valid?",
>
>
> ------------------------------
>
> In src/data/javascript-quiz.ts
> <https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/261#discussion_r990813547>
> :
>
> > @@ -1,4 +1,15 @@
>
>  const javascriptQuiz = [
>
> +  {
>
> +    Question:
>
> +      "What keyword is used to check whether a given property is valid or not?",
>
> +    Answer: "in",
>
> +    Distractor1: "is in",
>
> +    Distractor2: "exists",
>
> +    Distractor3: "lies",
>
> +    Explanation:
>
> +      "The in keyword is used to check whether the given property is valid or not in Javascript.",
>
>
> ⬇️ Suggested change
>
> -      "The in keyword is used to check whether the given property is valid or not in Javascript.",
>
> +      "The in keyword is used to check whether the given property in an object is valid or not.",
>
>
> ------------------------------
>
> In src/data/sql-quiz.ts
> <https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/261#discussion_r990813780>
> :
>
> > @@ -1,11 +1,24 @@
>
>  const sqlQuiz = [
>
>    {
>
> -    Question: "Which command is used in a 'WHERE' or 'HAVING' clause to limit the selected rows to the items when a column has a certain pattern of characters contained in it?",
>
> +    Question: "Which of the following allows you to uniquely identify a tuple?",
>
> +    Answer: "Super Key",
>
> +    Distractor1: "Schema",
>
> +    Distractor2: "Attribute",
>
> +    Distractor3: "Domain",
>
> +    Explanation:
>
> +      "Super Key is used to uniquely identify a tuple in a relation.",
>
> +    Link: "https://en.wikipedia.org/wiki/Superkey",
>
> +  },
>
> +
>
>
> please remove this extra space here
> ------------------------------
>
> In src/data/sql-quiz.ts
> <https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/261#discussion_r990813907>
> :
>
> > @@ -1,11 +1,24 @@
>
>  const sqlQuiz = [
>
>    {
>
> -    Question: "Which command is used in a 'WHERE' or 'HAVING' clause to limit the selected rows to the items when a column has a certain pattern of characters contained in it?",
>
> +    Question: "Which of the following allows you to uniquely identify a tuple?",
>
>
> ⬇️ Suggested change
>
> -    Question: "Which of the following allows you to uniquely identify a tuple?",
>
> +    Question: "In relational databases, which of the following allows you to uniquely identify a tuple?",
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/261#pullrequestreview-1135366786>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVR2T2UD6SHZQDIFKYNZTFTWCL4C7ANCNFSM6AAAAAARATKUZI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-12 17:47 UTC, P766-spec commented
@jdwilkin4 I have done the requested changes, please review it and merge the PR.

2022-10-12 19:29 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-12 19:30 UTC, merged