add a question to javascript file
freeCodeCamp/Developer_Quiz_Site pull request #264
Opened 2022-10-09 10:41 UTC by ddoyediran

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-09 10:42 UTC, ddoyediran commented
Please, let me know if there is anything to add or remove. Thank you @jdwilkin4

2022-10-09 17:23 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-09 17:23 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "In JavaScript, variables that are accessible throughout the program are called?",
```suggestion
      "In JavaScript, what is the name for variables that are accessible throughout the program?",
```

2022-10-09 17:23 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "Global variables are declared for accessibility throughout the program",
```suggestion
      "Global variables are declared and made accessible throughout the entire JavaScript program.",
```

2022-10-09 18:32 UTC, ddoyediran commented
Thank you! Done

2022-10-10 01:18 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-10 01:19 UTC, merged