added css questions
freeCodeCamp/Developer_Quiz_Site pull request #265
Opened 2022-10-09 12:06 UTC by Virajj28

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-09 17:31 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-09 17:31 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Question: "In CSS, how to center a div",
```suggestion
    Question: "In CSS, which of the following options is one way to center a div?",
```

2022-10-09 17:31 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Distractor3: "flexbox and margin:100%",
I think we need to be more explicit here

```suggestion
    Answer: "use  display: flex; on the parent container and  margin: auto; for the child container",
    Distractor1: "use  display: flex; on the parent container and  margin: 20px; for the child container",
    Distractor2: "use  display: flex; on the parent container and  margin: 50px; for the child container",
    Distractor3: "use  display: flex; on the parent container and  margin: 45%; for the child container",
```

2022-10-09 17:31 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +      "You can use flexbox and margin:auto to center a div in CSS.",
```suggestion
      "To center a div with CSS, apply display: flex; on the parent container and  margin: auto; for the child container.",
```

2022-10-09 17:31 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Question: "In CSS, 3em units are equivalent to how much px unit?",
```suggestion
    Question: "In CSS, 3em units are equivalent to how much in px units?",
```

2022-10-09 17:31 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Explanation: "Three em unit is equivalent to 40 pixels",
```suggestion
    Explanation: "3em is equivalent to 48 pixels.",
```

2022-10-09 18:08 UTC, Virajj28 commented
@jdwilkin4  Please can you merge branch to main as committed changes.

2022-10-10 01:20 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-10 01:20 UTC, merged