Added new question about agile methods
freeCodeCamp/Developer_Quiz_Site pull request #266
Opened 2022-10-09 16:08 UTC by PhilipeSousa

Added new question about agile methods, more specifically about Story Points.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-09 17:36 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-09 17:36 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +      "Which of the following is NOT one of notable features of story points?",
```suggestion
      "In Agile, which of the following is NOT one of notable features of story points?",
```

2022-10-09 17:36 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +    Distractor3: "Do not equate directly to time the task might take",
```suggestion
    Answer: "points are assigned in a odd-like sequence: 1, 3, 5, 7, 9...",
    Distractor1: "points represent the contributions of the whole team",
    Distractor2: "points estimate the ‘size’ of stories relative to each other",
    Distractor3: "points do not equate directly to time the task might take",
```

2022-10-09 17:36 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +      "The estimate the amount of effort required to deliver a user story are assigned using Fibonacci sequence",
```suggestion
      "Points estimate the amount of effort required to deliver a user story and are assigned using the Fibonacci sequence",
```

2022-10-09 19:07 UTC, PhilipeSousa commented
I made the adjustments, thank you for your attention.

2022-10-10 01:21 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-10 01:22 UTC, merged