Add a quiz question in `python-quiz.ts`
freeCodeCamp/Developer_Quiz_Site pull request #267
Opened 2022-10-09 16:32 UTC by MusfiqDehan

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #15

2022-10-09 17:55 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-09 17:55 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "In Python, which of the following option will reverse a_string='good' and make it 'doog'?",
```suggestion
      "In Python, which of the following options will reverse this string: sentence='freeCodeCamp rules'?",
```

2022-10-09 17:55 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Distractor3: "a_string.sort(reverse=True)",
```suggestion
    Answer: "sentence[::-1]",
    Distractor1: "reversed(sentence)",
    Distractor2: "sentence.reverse()",
    Distractor3: "sentence.sort(reverse=True)",
```

2022-10-09 17:55 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "<string>[start: stop: step] returns a slice of the string. <string>[:::] returns a copy of the entire string. <string>[::-1] returns a reversed copy of the string.",
Let's simplify this a bit.

```suggestion
      "In Python, [::-1] will return a reversed copy of the string.",
```

2022-10-09 18:41 UTC, MusfiqDehan commented
Hey @jdwilkin4 , I have implemented your suggested changes. Thank you much for guiding me. Feeling happy to contribute to a freecodecamp's project.

2022-10-10 01:22 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-10 01:23 UTC, merged

2022-10-10 03:55 UTC, jdwilkin4 commented
I removed the `Closes #15 ` from your pull request.
For future PR's please make sure not to close issues that are meant to stay open for multiple contributors. 👍

2022-10-10 04:45 UTC, MusfiqDehan commented
Ok, @jdwilkin4 . I didn't understand this before. I will keep this in my mind for the following PRs.