added a git quiz question
freeCodeCamp/Developer_Quiz_Site pull request #280
Opened 2022-10-10 15:21 UTC by tejeswar68

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-10 19:23 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-10 19:23 UTC, jdwilkin4 commented on .gitignore
> +
This empty space here is not needed.
Please remove it.

2022-10-10 19:23 UTC, jdwilkin4 commented on .husky/pre-commit
> +#npx pretty-quick --staged
Please do not make changes to this file.
Please revert back to the way it was.

2022-10-11 02:13 UTC, tejeswar68 commented
Resolved the changes!

2022-10-11 11:31 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-11 11:34 UTC, merged