feat: add new javascript quiz
freeCodeCamp/Developer_Quiz_Site pull request #283
Opened 2022-10-10 17:58 UTC by Evavic44

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-10 19:35 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-10 19:35 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "What is the result of the following: ('b' + 'a' + + 'cteri' + 'a').toLowerCase()",
```suggestion
      "In JavaScript, what is the result for the following code: ('b' + 'a' + + 'cteri' + 'a').toLowerCase()?",
```

2022-10-10 21:36 UTC, Evavic44 reviewed
Hey, @jdwilkin4. I've made the recommended changes. 🙂

2022-10-11 02:04 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-11 02:04 UTC, merged