Added another question in `python-quiz.ts`
freeCodeCamp/Developer_Quiz_Site pull request #297
Opened 2022-10-11 16:52 UTC by MusfiqDehan

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-11 22:00 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-11 22:00 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +          "numbers[-1], numbers[len(numbers)-1] and numbers.pop() all will return the last item of the numbers list.",
```suggestion
          "If you use negative indexing or the pop() method it will return the last item in the numbers list.",
```

2022-10-12 03:36 UTC, MusfiqDehan commented
Hi @jdwilkin4 ,

I have implemented your suggested changes. Thank you much for guiding me.

2022-10-12 04:41 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-12 04:41 UTC, merged