Add a python quiz question based on lambda function
freeCodeCamp/Developer_Quiz_Site pull request #300
Opened 2022-10-11 17:38 UTC by prashalruchiranga

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-11 22:19 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-11 22:19 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Explanation: "Lambda is an anynomous function that can have any number of arguments but only one expression, which is evaluated and returned.",
```suggestion
    Explanation: "A Lambda is an anonymous function that can have any number of arguments but only one expression, which is evaluated and returned.",
```

2022-10-12 01:03 UTC, prashalruchiranga commented on src/data/python-quiz.ts
> +    Explanation: "Lambda is an anynomous function that can have any number of arguments but only one expression, which is evaluated and returned.",
I have added the requested changes.

2022-10-12 02:04 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-12 02:04 UTC, merged