Added a html question on empty tag
freeCodeCamp/Developer_Quiz_Site pull request #328
Opened 2022-10-12 16:17 UTC by Utpalkant6204

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-12 19:18 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-12 19:18 UTC, jdwilkin4 commented on src/data/html-quiz.ts
> +      "In HTML, empty tags are those tags that don’t require a closing tag for completion.",
```suggestion
      "In HTML, empty tags are those tags that don’t require a closing tag.",
```

2022-10-13 16:14 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-13 18:10 UTC, Utpalkant6204 commented
Please merge if it don't need any change.

2022-10-14 00:47 UTC, merged