Added new MCQ to security quiz file with relevant freeCodeCamp link
freeCodeCamp/Developer_Quiz_Site pull request #344
Opened 2022-10-13 06:24 UTC by TannisthaBiswas

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-13 16:34 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-13 16:34 UTC, jdwilkin4 commented on src/data/security-quiz.ts
> +      "What is the full form os SSL?",
```suggestion
      "What does SSL stand for?",
```

2022-10-13 19:34 UTC, TannisthaBiswas commented
Changes incorporated. Hopefully you can merge now. 😊

2022-10-14 00:48 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-14 00:48 UTC, merged