Added QA Quiz Question
freeCodeCamp/Developer_Quiz_Site pull request #345
Opened 2022-10-13 06:37 UTC by shikharcodes

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Adds to #102

The added question covers regression tests.

2022-10-13 06:42 UTC, shikharcodes commented
Please add the "hacktoberfest-accepted" label before merging this, as I've contributed this under hacktoberfest 2022.

2022-10-13 16:39 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-13 16:39 UTC, jdwilkin4 commented on src/data/quality-assurance-quiz.ts
> +      "What do you mean by regression tests?",
```suggestion
      "What are regression tests?",
```

2022-10-14 00:53 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-14 00:53 UTC, merged