Bitwise operators in Python
freeCodeCamp/Developer_Quiz_Site pull request #346
Opened 2022-10-13 06:40 UTC by Sin-Sumit

Both are related to sorted method.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-13 06:41 UTC, Sin-Sumit commented
@jdwilkin4 Please review this one.

2022-10-13 16:48 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-13 16:48 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "The and keyword is used in Python to perform Bitwise NOT operations.",
Based on the answer you supplied I think the question should be which operator is used for that bitwise operation.
Let's go with this change

```suggestion
      "In Python, which operator is used to perform Bitwise NOT operations?",
    Answer: "~",
    Distractor1: "++",
    Distractor2: "!",
    Distractor3: "--",
    Explanation: 
      "The ~ operator is used in Python to perform Bitwise NOT operations.",
```

2022-10-13 16:48 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "The or keyword is used in Python to perform Bitwise OR operations.",
Based on the answer you supplied I think the question should be which operator is used for that bitwise operation.
Let's go with this change

```suggestion
      "In Python, which operator is used to perform Bitwise OR operations?",
    Answer: "|",
    Distractor1: ">>>",
    Distractor2: "<<<",
    Distractor3: "x",
    Explanation: 
      "The | operator is used in Python to perform Bitwise OR operations.",
```

2022-10-13 16:48 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "The and keyword is used in Python to perform Bitwise AND operations.",
Based on the answer you supplied I think the question should be which operator is used for that bitwise operation.
Let's go with this change

```suggestion
      "In Python, which operator is used to perform Bitwise AND operations?",
    Answer: "&",
    Distractor1: "{{",
    Distractor2: "&&",
    Distractor3: "<",
    Explanation: 
      "The & operator is used in Python to perform Bitwise AND operations.",
```

2022-10-14 00:54 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-14 00:54 UTC, merged