Add new question in general-cs-quiz and update modal-response
freeCodeCamp/Developer_Quiz_Site pull request #357
Opened 2022-10-13 09:37 UTC by humsarika

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes 
issue #29

2022-10-13 17:53 UTC, humsarika reviewed
@jdwilkin4, I've removed two linux-quiz question from security-quiz

2022-10-14 01:51 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-14 01:51 UTC, jdwilkin4 commented on src/data/general-cs-quiz.ts
> +  },
This question is already located in the IT quiz.
Please remove it here

2022-10-14 02:24 UTC, humsarika commented
@jdwilkin4  , I have done the requested changes.

2022-10-14 05:04 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-14 05:04 UTC, merged

2022-10-14 05:10 UTC, humsarika commented
@jdwilkin4 Thank you so much for merging my PR.