feat: add new javascript quiz
freeCodeCamp/Developer_Quiz_Site pull request #358
Opened 2022-10-13 09:39 UTC by Evavic44

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-13 17:39 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-13 17:39 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "In JavaScript, what operator has the highest precedence among these options",
```suggestion
      "In JavaScript, which operator has the highest precedence among these options?",
```

2022-10-14 01:55 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-14 01:55 UTC, merged

2022-10-14 02:35 UTC, Evavic44 commented
> Congrats on another contribution to our repository. 🎉
> 
> We look forward to future contributions. 👍

Thanks a lot, @jdwilkin4