Added a new Question
freeCodeCamp/Developer_Quiz_Site pull request #380
Opened 2022-10-14 10:40 UTC by abhishekiiitr

Type of variable in Python

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-14 22:55 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-14 22:55 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "In Python,if we have a='abhi' , then what is the result here : print(type(a))?",
```suggestion
      "In Python, if organization='freeCodeCamp', then what is the result here: print(type(organization))?",
```

2022-10-14 22:55 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "type() method returns class type of the argument(object) passed as parameter in Python",
```suggestion
      "Python's type() method returns the class type for the object.",
```

2022-10-15 04:33 UTC, abhishekiiitr reviewed
I have made the required changes, kindly merge the PR !

2022-10-15 05:47 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-15 05:47 UTC, merged