Added Accessibility Question
freeCodeCamp/Developer_Quiz_Site pull request #392
Opened 2022-10-14 21:20 UTC by preeformance

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Adds to #374 

Hey, so glad to see this as a new quiz category! I'm happy to add more questions but want to do things in the way that's easiest for the maintainers to keep up with. Is one question per PR the way to go or would multiple at once be a better option?

2022-10-14 22:06 UTC, jdwilkin4 commented
Hi @preeformance ! 

Either option works fine.
If you have a list of questions right now, then you can add all of that to the same PR.
When that is merged and you think of new questions then you can create a new PR for those 👍

2022-10-14 22:22 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-14 22:22 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +    Question: "What attribute makes images accessible for people using screen readers?",
```suggestion
    Question: "Which attribute makes images accessible for people using screen readers?",
```

2022-10-14 22:22 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +      "With one attribute, alt, we are able to make the image accessible for screen reader users.",
```suggestion
      "The alt attribute provides short descriptive text for images and the text is read aloud by a screen reader.",
```

2022-10-15 18:56 UTC, preeformance commented
I'll create a new PR after I write a few more questions. Thanks!

2022-10-15 20:16 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-15 20:16 UTC, merged