Add new JavaScript questions
freeCodeCamp/Developer_Quiz_Site pull request #40
Opened 2022-02-04 01:20 UTC by amehi0index

Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

2022-02-05 05:26 UTC, jdwilkin4 requested changes
HI @amehi0index ! 

Thank you for your questions! 
Please review my requested changes 👍

2022-02-05 05:26 UTC, jdwilkin4 commented on src/data/full-quiz.js
> +    "A variable that has not been assigned a value is of type undefined",
Proposed fix:
In JavaScript, a variable that has been declared but not assigned a value is known as undefined.

2022-02-05 05:26 UTC, jdwilkin4 commented on src/data/full-quiz.js
> +    "Null value is assigned to a variable to represent that the variable exists, but has no type or value.",
Proposed fix:
In JavaScript, null represents the absence of a value.

2022-02-05 05:26 UTC, jdwilkin4 commented on src/data/full-quiz.js
> +    Link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch",
Whenever possible we like to use freeCodeCamp resources first before moving to MDN.

Proposed fix:
Link:"https://www.freecodecamp.org/news/javascript-switch-case-js-switch-statement-example/",

2022-02-05 05:36 UTC, jdwilkin4 commented
Also, please make sure to update the format for your questions so the key value pairs are in the same line.

Please follow this example:
```
  {
    Question: "What is a maximum length for a filename under Linux?",
    Answer: "255 Bytes",
    Distractor1: "225 Bytes",
    Distractor2: "235 Bytes",
    Distractor3: "295 Bytes",
    Explanation: "The maximum length for a file name is 255 bytes. The maximum combined length of both the file name and path name is 4096 bytes.",
    Link: "https://www.ibm.com/docs/en/spectrum-protect/8.1.9?topic=parameters-file-specification-syntax",
  },
```

2022-02-07 18:18 UTC, amehi0index reviewed
Made changes as per your request.

2022-02-08 00:59 UTC, jdwilkin4 commented
Hi @amehi0index ! 

I am not seeing your recent changes committed in this PR. 
You might need to double check and make sure your changes you made locally are showing up in your remote repo on GitHub. 
Let me know if you have any questions! 😃

2022-02-09 20:10 UTC, jdwilkin4 approved these changes
LGTM! 👍

2022-02-09 20:11 UTC, merged

2022-02-09 20:45 UTC, amehi0index commented
Thank you!