add nan js question
freeCodeCamp/Developer_Quiz_Site pull request #417
Opened 2022-10-16 16:59 UTC by OmarCardoze

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-16 18:30 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-16 18:30 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "In JavaScript, What is the result if we do a typeof to NaN?",
```suggestion
      "In JavaScript, what is the result for typeof NaN?",
```

2022-10-16 18:30 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Distractor2: "Number",
distractor are for wrong answers only

```suggestion
    Distractor2: "String",
```

2022-10-16 18:30 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "Because NaN is a property of the Number object in JS.",
```suggestion
      "typeof NaN will return number because NaN is a property of the Number object in JavaScript.",
```

2022-10-16 18:30 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Answer: "Number",
```suggestion
    Answer: "number",
```

2022-10-16 20:45 UTC, OmarCardoze commented
Changes added, it's my first contribution thank you very much!

2022-10-17 03:14 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-17 03:14 UTC, merged