Updated python-quiz.ts
freeCodeCamp/Developer_Quiz_Site pull request #421
Opened 2022-10-16 17:48 UTC by anish853

Added question on python kindly review it and merge it.

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-16 17:49 UTC, anish853 commented
Kindly merge it.

2022-10-16 18:46 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-16 18:46 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "One line expression function in python is called as?",
```suggestion
      "In Python, what are anonymous functions called?",
```

2022-10-16 18:46 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Distractor1: "Lambda function",
distractor are only for wrong answers

```suggestion
    Distractor1: "type function",
```

2022-10-16 18:46 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Distractor3: "Nothing",
```suggestion
    Distractor3: "sorted functions",
```

2022-10-16 23:27 UTC, anish853 commented
Problem has been resolved. Kindly merge it.

2022-10-17 03:19 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-17 03:19 UTC, merged