added a question in linux-quiz.ts
freeCodeCamp/Developer_Quiz_Site pull request #426
Opened 2022-10-16 20:12 UTC by shubhsinha

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-16 20:19 UTC, shubhsinha commented
added a question for developer quiz site

2022-10-17 03:37 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-17 03:37 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Question: "Which of the following commands is used to calculate a file's total lines, words, and characters?",
```suggestion
    Question: "Which of the following Linux commands calculates the total number of lines, words, and characters in a file?",
```

2022-10-17 03:37 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +      "A file's total number of lines, words, and characters can be determined with the wc command.",
```suggestion
      "The wc command calculates the total number of lines, words, and characters in a file.",
```

2022-10-17 09:30 UTC, shubhsinha commented
updated as requested

2022-10-17 19:46 UTC, merged