Added question
freeCodeCamp/Developer_Quiz_Site pull request #429
Opened 2022-10-16 20:36 UTC by shubhsinha

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-16 20:37 UTC, shubhsinha commented
added question

2022-10-17 03:58 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-17 03:58 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
>  ];
This questions is missing a link field.
All questions are required to have a link.
Please use a freeCodeCamp resource, official documentation or wikipedia article

2022-10-17 03:58 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +      "The best datatype to use to store a string with up to 255 characters is which of the following?",
```suggestion
      "In SQL, which data type is used to store a string with up to 255 characters?",
```

2022-10-17 03:58 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +    Answer: "TINY TEST",
The last word should be text and it should be all one word

```suggestion
    Answer: "TINYTEXT",
```

2022-10-17 03:58 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +    Distractor1: "TEXT",
```suggestion
    Distractor1: "STRING",
```

2022-10-17 03:58 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +      "A string in TINY TEXT can be up to 255 characters or 255 bytes long.",
```suggestion
      "TINYTEXT can store up to 255 bytes and can be used for text like captions or summaries.",
```

2022-10-17 09:01 UTC, closed without merging