Added a question to general-html-quiz.ts
freeCodeCamp/Developer_Quiz_Site pull request #442
Opened 2022-10-17 17:38 UTC by Harshit-Raj-14

Added a question based on the application of href tag in an html document code.

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

Please add a **hacktoberfest accepted** tag after merged.

Thanks for the opportunity.

2022-10-17 22:16 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-17 22:16 UTC, jdwilkin4 commented on src/data/html-quiz.ts
> +    "Which of the following is the correct way of creating an hyperlink in HTML?",
```suggestion
    "Which of the following is the correct way of creating an anchor element in HTML?",
```

2022-10-17 22:16 UTC, jdwilkin4 commented on src/data/html-quiz.ts
> +    Distractor3: "<a link=“ www.freecodecamp.org” freeCodeCamp > </a>",
let's just go with single quotes here

```suggestion
    Answer: "<a href= 'www.freecodecamp.org'> freeCodeCamp </a>",
    Distractor1: "<a>www.freecodecamp.org <freeCodeCamp /a>",
    Distractor2: "<a href='www.freecodecamp.org' freeCodeCamp /a>",
    Distractor3: "<a link='www.freecodecamp.org' freeCodeCamp > </a>",
```

2022-10-17 22:16 UTC, jdwilkin4 commented on src/data/html-quiz.ts
> +      "In HTML a href tag is used to hyperlink text as shown in the given syntax. <a href= “www.link_name.com”> hyperlinked_text </a>"
```suggestion
      "In HTML, an anchor element is used to create links on a a web page. Here is the correct syntax: <a href= 'www.freecodecamp.org'> freeCodeCamp </a>"
```

2022-10-17 22:16 UTC, jdwilkin4 commented on src/data/html-quiz.ts
> +      "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-href"
Whenever possible, it is always best to use a freeCodeCamp resources first

```suggestion
      "https://www.freecodecamp.org/news/the-html-a-tag-anchor-tag-example-code/"
```

2022-10-17 22:17 UTC, jdwilkin4 commented on src/data/html-quiz.ts
> +      "In HTML a href tag is used to hyperlink text as shown in the given syntax. <a href= “www.link_name.com”> hyperlinked_text </a>"
Also, this should fix your syntax issue

2022-10-18 04:27 UTC, Harshit-Raj-14 commented
> Thank you for your contribution!
> 
> Please review the requested changes. Once those changes have been implemented, then we can merge your PR into main. 👍

Thank you, and I have made the necessary changes you have suggested.
Hopefully now the PR can be merged.

Also, please add a **hacktoberfest accepted** tag after merged.

Thanks for the opportunity.

2022-10-18 05:50 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-18 05:52 UTC, jdwilkin4 commented
Also, I resolved your other syntax error.
In the future, make sure to pay close attention to syntax errors 👍

2022-10-18 05:52 UTC, merged