added new question on chmod in linux
freeCodeCamp/Developer_Quiz_Site pull request #444
Opened 2022-10-17 18:31 UTC by PranjalSK03

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-17 23:05 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-17 23:05 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Question: "Say a file named 'list' has has intial file permissions as '-rwxrwxrwx', A person wants to change its permissions using 'chmod' such that GROUP and OTHER can only read it, neither writ
This question is a little to long. Let's shorten it. 
```suggestion
    Question: "In Linux, which command is used to remove the writing and executing permissions for 'group' and 'other'?",
```

2022-10-17 23:05 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +      "'chmod go-wx list' will make 'g' group and 'o' other, '-' remove 'w' the writing and 'x' the executing permission only",
```suggestion
      "'The chmod go-wx list is used to remove the writing and executing permissions for 'group' and 'other' for a file named list.",
```

2022-10-17 23:05 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Link: "https://linuxize.com/post/chmod-command-in-linux/",
Please use freeCodeCamp resource here

2022-10-17 23:05 UTC, jdwilkin4 commented on src/stylesheets/HomepageRow.css
> +
Please remove this comment since this commenting style has not been established in other parts of the app 👍

2022-10-18 04:17 UTC, PranjalSK03 reviewed
updated the question in accordance to requirements

2022-10-18 04:18 UTC, PranjalSK03 commented
please see if any further changes required.

2022-10-18 05:54 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-18 05:55 UTC, merged