Update python-quiz.ts
freeCodeCamp/Developer_Quiz_Site pull request #447
Opened 2022-10-17 21:48 UTC by shubhsinha

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-17 21:49 UTC, shubhsinha commented
added a Python question

2022-10-17 23:08 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-17 23:08 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Question: "What will be the output of command, round(0.6)-round(-0.6)?",
```suggestion
    Question: "In Python, what will be the output for the following code: print(round(0.6)-round(-0.6))?",
```

2022-10-17 23:08 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Explanation: "round() function in Python, rounds off the number away from 0 to the nearest integer, round(0.6) = 1 and round(-0.6) = -1. So 1-(-1)=2.",
```suggestion
    Explanation: "In Python, round(0.6) will round up to 1 and round(-0.6) will round down to -1. The result for round(0.6)-round(-0.6) will be 2.",
```

2022-10-17 23:35 UTC, shubhsinha commented
updated as asked

2022-10-18 01:05 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-18 01:06 UTC, merged