added-agile-questions
freeCodeCamp/Developer_Quiz_Site pull request #460
Opened 2022-10-18 14:41 UTC by KmKalpana

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-18 14:44 UTC, KmKalpana commented
I have added agile-quiz-questions

2022-10-18 22:22 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-18 22:22 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +    Link: "https://www.agilealliance.org/agile101/",
Please only use freeCodeCamp resources for the link field.

2022-10-18 22:22 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +    Link: "https://www.planview.com/resources/articles/fdd-agile/",
Please only use freeCodeCamp resources for the link field.

2022-10-18 22:22 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +      "What is an iterative development methodology, where both development and testing activities are concurrent.",
This wording is a little to close to here
https://sceweb.sce.uhcl.edu/helm/WEBPAGE-AgileTesting


```suggestion
      "What is the name for the process that focuses on continuously building, testing, and gathering feedback for software products?",
```

2022-10-18 22:22 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +      "Agile is an iterative development methodology, where both development and testing activities are concurrent.",
```suggestion
      "Agile is a project management process that focuses on continuously building, testing, and gathering feedback for software products.",
```

2022-10-18 22:22 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +    Questions: "FFD Stands for?",
```suggestion
    Questions: "In Agile, what does FFD stand for?",
```

2022-10-18 22:22 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +      "Feature Driven Development (FDD) involves designing and building features. The difference between FDD and other Agile Development Methodologies is that the features are developed in specific a
```suggestion
      "Feature Driven Development (FDD) is the practice of incrementally developing and frequently releasing new features for software products.",
```

2022-10-19 04:06 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-19 04:07 UTC, merged