Adding sql quiz questions
freeCodeCamp/Developer_Quiz_Site pull request #461
Opened 2022-10-18 15:05 UTC by KmKalpana

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-18 22:34 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-18 22:34 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +  },
These questions are already in this PR
https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/460

Please remove them here

2022-10-18 22:34 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +     Link:"https://afteracademy.com/blog/what-is-join-in-dbms-and-what-are-its-types/",
Please only user freeCodeCamp resources or official documentation here

2022-10-18 22:34 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +     Link:"https://mode.com/sql-tutorial/sql-outer-joins/",
Please only user freeCodeCamp resources or official documentation here

2022-10-18 22:34 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +      "Which of the following is one of the basic approaches for joining tables?",
```suggestion
      "In SQL, which of the following is an approach for joining tables?",
```

2022-10-18 22:34 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +        "The SQL subquery is a SELECT query that is embedded in the main SELECT statement. In many cases, a subquery can be used instead of a JOIN.",
```suggestion
        "In SQL, you can use a subquery, union join or natural join to join multiple tables together.",
```

2022-10-18 22:34 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +      "What type of join is needed when you wish to include rows that do not have matching values?",
```suggestion
      "In SQL, what is the name of the join that will return matched and unmatched values from a table?",
```

2022-10-18 22:34 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +        "OUTER JOIN is the only join which shows the unmatched rows.",
```suggestion
        "OUTER JOIN is used to return matched and unmatched values from a table.",
```

2022-10-19 01:03 UTC, KmKalpana commented
modified sql-quiz-questions

2022-10-19 03:59 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +  },
I pushed up a commit to remove these duplicate questions.
But in the future, you want to be extra careful and double check your PR's to make sure you are not adding duplicate content 👍

2022-10-19 04:02 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-19 04:02 UTC, merged