Update python-quiz.ts
freeCodeCamp/Developer_Quiz_Site pull request #485
Opened 2022-10-20 07:12 UTC by dhruvjain896

Added one question

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

Added One Question on the concept of python math.trunc in ./src/data/python-quiz.ts

2022-10-20 13:42 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-20 13:42 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Question: "What is the result of math.trunc(3.1)?",
```suggestion
    Question: "In Python, what is the result for math.trunc(3.1)?",
```

2022-10-20 13:42 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Distractor2: "3",
distractors should be for wrong answers only

```suggestion
    Distractor2: "3.14",
```

2022-10-20 13:42 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Distractor1: "3.0",
```suggestion
    Distractor1: "3.5",
```

2022-10-20 13:42 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +    Explanation: "The integral part of the floating point number is returned.",
```suggestion
    Explanation: "In Python, math.trunc() will return the truncated integer part of the number. When the number is positive, math.trunc() is similar to the .floor() method. But if the number is negative, math.trunc() is similar to the .ceil() method",
```

2022-10-22 18:20 UTC, dhruvjain896 commented
Hi @jdwilkin4 I committed the requested changes.

2022-10-23 00:16 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-23 00:16 UTC, merged