Add JavaScript export question
freeCodeCamp/Developer_Quiz_Site pull request #490
Opened 2022-10-20 15:22 UTC by richardoey

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

2022-10-21 03:25 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-21 03:25 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#exporting_module_features"
```suggestion
    Link: "https://www.freecodecamp.org/news/javascript-modules-explained-with-examples/#"
```

2022-10-21 03:25 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "In JavaScript, which keyword to make a variable, function, class or object accessible to other module?",
```suggestion
      "In JavaScript, which keyword is used to make portions of code accessible to other modules.?",
```

2022-10-21 03:25 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "Before we can get access to module features, the first thing we need to do is 'export' them.",
```suggestion
      "The export keyword is used to make it possible to access small portions of code in other modules",
```

2022-10-21 13:32 UTC, richardoey commented
I have changes based on your feedback. Thanks a lot! There are lot of grammar mistakes from me before. Thank you for giving your time checking it. I also has resolved the conflict after pulling from main branch

2022-10-22 00:22 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-22 00:22 UTC, merged