chore: added questions on cryptography in security-quiz.ts
freeCodeCamp/Developer_Quiz_Site pull request #513
Opened 2022-10-22 07:12 UTC by J-ell

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #104

2022-10-22 16:49 UTC, jdwilkin4 commented
I have removed the `Closes #104` from your PR.
Please make sure not to include that because we want this issue to stay open for multiple contributors.

2022-10-22 16:56 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-22 16:56 UTC, jdwilkin4 commented on src/data/security-quiz.ts
> +    Distractor3: "HTTPS uses port 80 by default, therfore it is more secured",
```suggestion
    Distractor3: "HTTPS uses port 80 by default, therefore it is more secure",
```

2022-10-22 16:56 UTC, jdwilkin4 commented on src/data/security-quiz.ts
> +    Question: "What does GPG stands for?",
```suggestion
    Question: "What does GPG stand for?",
```

2022-10-23 07:21 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-23 07:21 UTC, merged

2022-10-23 17:23 UTC, J-ell commented
> Congrats on another contribution to our repository. 🎉 We look forward to future contributions. 👍

Thank you for always making the experience awesome