commit message
freeCodeCamp/Developer_Quiz_Site pull request #530
Opened 2022-10-23 09:45 UTC by tripura-kant

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org). 
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

Added Linux question for [Developer_Quiz_Site](https://github.com/freeCodeCamp/Developer_Quiz_Site)

2022-10-23 09:53 UTC, tripura-kant commented
Added Linux question . Kindly review .

2022-10-23 15:29 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-23 15:29 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Question: "In Linux, which command you can use to find memory being used by Linux?",
```suggestion
    Question: "Which command finds memory being used by Linux?",
```

2022-10-23 15:29 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +      "The top command is used to display dynamic real-time information. You can use free-m ,htop ,top or vmstat to find memory being used by Linux.",
```suggestion
      "The top command is used to display dynamic real-time information. You can use free-m, htop, top or vmstat to find memory being used by Linux.",
```

2022-10-23 15:34 UTC, tripura-kant commented
Changes are made. Thanks for review.

2022-10-23 17:21 UTC, jdwilkin4 commented
@tripura-kant 

It looks like you accidentally created a new file. 
Please remove that extra file and only change the existing quiz file

2022-10-23 19:13 UTC, tripura-kant commented
Yes, the extra file has been deleted now. Kindly review @jdwilkin4

2022-10-24 02:15 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-24 02:16 UTC, merged