Added Attribute  Selector question in css-quiz.ts
freeCodeCamp/Developer_Quiz_Site pull request #535
Opened 2022-10-23 15:41 UTC by Ankit-Aslekar

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-24 02:41 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-24 02:41 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +      "what is syntax of Attribute Selector in CSS?",
```suggestion
      "Which of the following is the correct syntax for an attribute selector in CSS?",
```

2022-10-24 02:41 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Answer: "container[attribute="value"]",
```suggestion
    Answer: "selector[attribute='value']",
```

2022-10-24 02:41 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +      "It selects elements with an attribute with specefic value .",
```suggestion
      "The correct syntax for an attribute selector in CSS is selector[attribute='value'].",
```

2022-10-24 05:19 UTC, Ankit-Aslekar commented
@jdwilkin4 thanks for reviewing, I too liked the changes and updated PR, please have look again

2022-10-24 05:50 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Answer: "container[attribute="value"]",
@Ankit-Aslekar 

You have to use single quotes like suggested above to fix the linting errors

2022-10-24 05:52 UTC, jdwilkin4 requested changes

2022-10-24 05:52 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Answer: "selector[attribute="value"]",
```suggestion
    Answer: "selector[attribute='value']",
```

2022-10-26 00:55 UTC, jdwilkin4 commented
I went ahead and resolved the syntax linting error

2022-10-26 00:56 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-26 00:56 UTC, merged