Added Agile quiz question
freeCodeCamp/Developer_Quiz_Site pull request #544
Opened 2022-10-24 07:41 UTC by prasad-333

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

issue#103

2022-10-24 19:09 UTC, prasad-333 commented
Added 2 more agile questions.

2022-10-24 23:38 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-24 23:38 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +      "Scrum Master is responsible for establishing scrum within team & at organization level. They achieve this by enabling the Scrum Team to improve its practices, within scrum framework and help t
I think it is fine to leave off the last sentence. If users want to learn more, then they can always click on the learn more link in the quiz. 
```suggestion
      " The Scrum Master is responsible for establishing scrum within the team & organizational level.",
```

2022-10-25 16:20 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-25 16:20 UTC, merged