Update sql-quiz.ts
freeCodeCamp/Developer_Quiz_Site pull request #569
Opened 2022-10-26 07:00 UTC by Suhas2002

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-26 21:57 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-26 21:57 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +    Answer: "UNIQUE",
But this is a constraint. 

```suggestion
    Answer: "UPDATE",
```

2022-10-26 21:57 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +    Distractor3: "UPDATE",
this is supposed to be the correct answer though. remember that distractors are for wrong answers only

```suggestion
    Distractor3: "UNIQUE",
```

2022-10-26 21:57 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +    Explanation: "In SQL, The UPDATE statement is used to modify the existing records in a table.  Hence, it is not a constraint",
```suggestion
    Explanation: "In SQL, the UPDATE statement is used to modify the existing records in a table and therefore not a constraint.",
```

2022-10-27 10:56 UTC, Suhas2002 commented
Hey @jdwilkin4, I have made the changes you asked for

2022-10-27 18:50 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-27 18:50 UTC, merged