Add the Question in JS Guess the Sum of expression?
freeCodeCamp/Developer_Quiz_Site pull request #587
Opened 2022-10-27 12:03 UTC by Shaik-mohd-huzaifa

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-27 19:20 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-27 19:20 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Question: "What is the Sum of this Expression (true + 34)",
```suggestion
    Question: "In JavaScript, what is the result for the following code: console.log(true + 34)?",
```

2022-10-27 19:20 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Distractor3: "35",
distractors are for wrong answers only

```suggestion
    Distractor3: "25",
```

2022-10-27 19:20 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "Here the True gets converted to a number and gives out 1. Because 0 = false and 1 = true",
```suggestion
      "Since true is converted to the number 1, then true + 34 would result in 35.",
```

2022-10-28 17:20 UTC, Shaik-mohd-huzaifa reviewed
Changes are done now you can accept the pull request

2022-10-28 20:20 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-28 20:21 UTC, merged