Add a Question about how a commit message should be ?
freeCodeCamp/Developer_Quiz_Site pull request #595
Opened 2022-10-28 17:02 UTC by Shaik-mohd-huzaifa

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-28 20:43 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-28 20:43 UTC, jdwilkin4 commented on src/data/git-quiz.ts
> +    Link: ""
Please do not leave this field blank
All question submissions need to have a resource

 ```suggestion
    Link: "https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/"
```

2022-10-28 20:43 UTC, jdwilkin4 commented on src/data/git-quiz.ts
> +    Distractor2: "It should be in oneword",
```suggestion
    Distractor2: "It should be in one word",
```

2022-10-28 20:43 UTC, jdwilkin4 commented on src/data/git-quiz.ts
> +    Question: "How Should a Git commit message be?",
```suggestion
    Question: "In Git, what does a good commit message look like?",
```

2022-10-28 20:43 UTC, jdwilkin4 commented on src/data/git-quiz.ts
> +    Distractor1: "It should be longer",
```suggestion
    Distractor1: "It should be long",
```

2022-10-29 08:02 UTC, Shaik-mohd-huzaifa commented
Applied Changes

2022-10-29 15:10 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-29 15:10 UTC, merged