Add a linux question about how to list last lines of a file
freeCodeCamp/Developer_Quiz_Site pull request #602
Opened 2022-10-28 18:13 UTC by Shaik-mohd-huzaifa

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-28 21:02 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-28 21:02 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Question: "In Linux, which command is used to list last 10 lines of a file",
```suggestion
    Question: "In Linux, which command is used to list the last 10 lines of a file?",
```

2022-10-28 21:02 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Explanation: "This Command is used to list last 10 lines of a file",
```suggestion
    Explanation: "tail -10 filename is used to list the last 10 lines of a file.",
```

2022-10-28 21:02 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Link: ""
The link field cannot be empty

```suggestion
    Link: "https://www.freecodecamp.org/news/the-linux-commands-handbook/"
```

2022-10-29 03:33 UTC, Shaik-mohd-huzaifa commented
Applied Changes

2022-10-29 10:28 UTC, Shaik-mohd-huzaifa commented
Applied Changes

2022-10-29 15:39 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-29 15:39 UTC, merged