Add linux question to create a new file and open in vi editor
freeCodeCamp/Developer_Quiz_Site pull request #603
Opened 2022-10-28 18:18 UTC by Shaik-mohd-huzaifa

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-10-28 21:04 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-28 21:04 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Link: ""
The link field cannot be blank

```suggestion
    Link: "https://www.freecodecamp.org/news/learn-vim-beginners-tutorial/"
```

2022-10-28 21:04 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +      "This command is used to create a new file using terminal and open it in the Vim editor.",
```suggestion
      "vi filename.extention is used to create a new file using the terminal and open it in the Vim editor.",
```

2022-10-29 03:32 UTC, Shaik-mohd-huzaifa reviewed
Applied Changes

2022-10-29 15:40 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-29 15:42 UTC, merged