Added quality assurance and testing questions
freeCodeCamp/Developer_Quiz_Site pull request #612
Opened 2022-10-30 08:15 UTC by jayantpranjal0

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

2022-10-30 15:38 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-30 15:38 UTC, jdwilkin4 commented on src/data/quality-assurance-quiz.ts
> +    Distractor1:"With TDD application logic precedes test logic",
```suggestion
    Distractor1:"With TDD, application logic precedes test logic",
```

2022-10-30 20:00 UTC, jayantpranjal0 commented
Thank you for your recommendation. I have changed the file as per your recommendation. Please review/merge the PR.

2022-10-31 01:20 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-31 01:20 UTC, merged