Add new Css questions
freeCodeCamp/Developer_Quiz_Site pull request #633
Opened 2022-11-11 18:10 UTC by Shaik-mohd-huzaifa

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-11-12 16:02 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-11-12 16:02 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Question: "In CSS, What will this pseudo class selector do? :nth-child(2)",
```suggestion
    Question: "In CSS, what will the following pseudo class selector do :nth-child(2)?",
```

2022-11-13 17:34 UTC, Shaik-mohd-huzaifa commented
Changes Applied

2022-11-14 00:05 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-11-14 00:06 UTC, merged