Css question 1
freeCodeCamp/Developer_Quiz_Site pull request #634
Opened 2022-11-11 18:11 UTC by Shaik-mohd-huzaifa

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-11-12 16:06 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-11-12 16:06 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +      "Flex is a shorthand property for all these three properties: flex-grow, flex-shrink, and flex-basis.",
```suggestion
      "Flex is a shorthand property for these three properties: flex-grow, flex-shrink, and flex-basis.",
```

2022-11-12 16:06 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Distractor3: "flex-direction, flex-wrap, and flex-flow",
we don't want two answers to be identical

```suggestion
    Distractor3: "flex-direction, order, and flex-reverse",
```

2022-11-12 16:06 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Question: "In Linux, How to end an if statement?",
```suggestion
    Question: "In Linux, which one is the correct keyword used to end an if statement?",
```

2022-11-12 16:06 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Link: "https://www.geeksforgeeks.org/conditional-statements-shell-script/"
We only accept freeCodeCamp resources or official documentation

2022-11-12 16:06 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Explanation: "fi keyword is used to end an if statement in Linux.",
```suggestion
    Explanation: "The fi keyword is used to end an if statement in Linux.",
```

2022-11-14 00:08 UTC, jdwilkin4 requested changes

2022-11-14 00:08 UTC, jdwilkin4 commented on src/data/linux-quiz.ts
> +    Link: "https://www.geeksforgeeks.org/conditional-statements-shell-script/"
This link still needs to be changed

2022-11-14 12:55 UTC, Shaik-mohd-huzaifa reviewed
Check if the link is Changed or not

2022-11-15 07:07 UTC, jdwilkin4 commented
It looks like you ran into some issues when you tried to resolve a merge conflict because it looks like you deleted both of your questions here.

If you click on the Files Change tab for the PR, it will show you the current state for the PR.
<img width="479" alt="Screen Shot 2022-11-14 at 11 06 04 PM" src="https://user-images.githubusercontent.com/67210629/201852276-1d2c46af-4f32-4007-8d13-edeb7f884fd3.png">

<img width="866" alt="Screen Shot 2022-11-14 at 11 06 24 PM" src="https://user-images.githubusercontent.com/67210629/201852323-e93a2708-5273-401f-8e0c-1f9ec7aaad83.png">

As maintainer, I am able to go in and undo these deletions.
But in the future, if you are curious about the current state of your PR, you can view all changed files in the Files Changed tab 👍

2022-11-15 07:16 UTC, jdwilkin4 approved these changes

2022-11-15 07:17 UTC, merged