Javascript question v2 2
freeCodeCamp/Developer_Quiz_Site pull request #638
Opened 2022-11-11 18:12 UTC by Shaik-mohd-huzaifa

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-11-12 16:33 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-11-12 16:33 UTC, jdwilkin4 commented on src/data/css-quiz.ts
> +    Link: "https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction"
This question was used in another PR you submitted.
Please remove it here

2022-11-12 16:33 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Link: "https://stackoverflow.com/questions/4797286/are-braces-necessary-in-one-line-statements-in-javascript"
Let's go with this rewording of the question and answers

```suggestion
    Question:
      "In JavaScript, which of the following is the correct syntax for a one line if statement?",
    Answer: "if(5>4) console.log("This is true");",
    Distractor1: "if(5>4) <<>> console.log("This is true"); ",
    Distractor2: "if[5>4] console.log("This is true");",
    Distractor3: "((if(5>4) console.log("This is true")));",
    Explanation:
      "In JavaScript, you can create a one line if statement without the curly braces using this syntax: if (condition is true) // short one line of code is executed",
    Link: "https://www.freecodecamp.org/news/javascript-if-else-and-if-then-js-conditional-statements/"
```

2022-11-13 17:21 UTC, Shaik-mohd-huzaifa reviewed
Changes applied

2022-11-13 17:40 UTC, closed without merging