Question about sorting algorithms
freeCodeCamp/Developer_Quiz_Site pull request #651
Opened 2022-12-30 18:23 UTC by sotoblanco

This question allows evaluation of the understanding of why sorting algorithms are important, which might increase the ability of the student to learn it.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2023-01-01 23:46 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-01-01 23:46 UTC, jdwilkin4 commented on src/data/general-cs-quiz.ts
> +    Question: "Why Sorting Algorithms are Important?" ,
```suggestion
    Question: "Why are sorting algorithms important in programming?" ,
```

2023-01-02 00:42 UTC, sotoblanco commented
Thank you

2023-01-02 00:43 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-01-02 00:43 UTC, merged