Added a new SQL question
freeCodeCamp/Developer_Quiz_Site pull request #688
Opened 2023-09-30 21:58 UTC by btrezzy

**Checklist:**
- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org/).
- [ ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (not a vague title like Update index.md)

2023-09-30 23:32 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-09-30 23:32 UTC, jdwilkin4 commented on src/data/sql-quiz.ts
> +    Question: "In SQL, which of the following LIKE operator finds any values that have 'or' at any position?",
```suggestion
    Question: "In SQL, which of the following wildcards combined with the LIKE operator finds any value that has 'or' at any position?",
```

2023-10-01 03:29 UTC, btrezzy commented
Changes made, thanks for the feedback!

2023-10-01 07:30 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-10-01 07:31 UTC, merged