fix(issue#29): added new CS questions
freeCodeCamp/Developer_Quiz_Site pull request #71
Opened 2022-06-19 21:35 UTC by a-cole55

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2022-06-19 21:43 UTC, a-cole55 commented
two new CS questions added to full-quiz.ts file

2022-06-20 01:57 UTC, jdwilkin4 commented
HI @a-cole55 ! 

It looks like you have some merge conflicts and your branch is 12 commits ahead and 1 commit behind the fcc main branch. 
I would read through this github issue to resolve the issue
https://stackoverflow.com/questions/41283955/github-keeps-saying-this-branch-is-x-commits-ahead-y-commits-behind

Hope that helps!

2022-06-24 00:07 UTC, jdwilkin4 requested changes
Left a few comments 👍

2022-06-24 00:07 UTC, jdwilkin4 commented on src/data/full-quiz.ts
> +      "Computers are simplistic and understand binary, other languages (such as Python, Java, etc) were created to help humans write instructions for computers and interpret it.",
I think the explanation should be two sentences. 

Proposed solution: 
Computers are simplistic and understand binary. Programming languages such as Python and Java were created to help humans write instructions for computers and interpret it.

2022-06-24 00:07 UTC, jdwilkin4 commented on src/data/full-quiz.ts
> +      "Where is the CPU located in a computer?",
This question already exists in the database. 
Please remove it. 👍

2022-07-01 20:10 UTC, merged