Try to set up pre-commit hooks
freeCodeCamp/Developer_Quiz_Site pull request #78
Opened 2022-07-02 17:14 UTC by a2937

I found the information on https://www.inkoop.io/blog/setup-eslint-for-react-with-prettier-pre-commit-and-vscode/

Hopefully it'll work nicely.

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #77

Pre-commit was intimidating but pretty-quick seems pretty easy? I know it's not exactly what you want , but it could work maybe?

2022-07-04 20:24 UTC, jdwilkin4 requested changes
I tested this locally by temporarily disabling my Prettier config and I was still able push up a commit where I changed the formatting to the button component. 

I am not able to get the command to run before pushing the commit.
Maybe there is an addition configuration or change needed for pretty-quick
https://github.com/azz/pretty-quick

2022-07-04 21:13 UTC, jdwilkin4 commented on src/components/Button.tsx
> +      let classes = "btn-default";
I made changes to this button file to test out the pre commit hook.

You can use this file to test out your pre commit hook changes.
When successful, the pre commit hook will format it even if the user does not have es lint or prettier installed locally on their code editor. 

I also used [Option 1 ](https://prettier.io/docs/en/precommit.html) for my forked copy and recorded the pre commit results in the terminal. 

https://user-images.githubusercontent.com/67210629/177216862-41da756d-3df8-4268-a350-f1b79c75d84f.mov

Hope that helps!

2022-07-09 18:36 UTC, jdwilkin4 requested changes
I ran through [the pretty-quick instructions](https://prettier.io/docs/en/precommit.html#option-2-pretty-quickhttpsgithubcomazzpretty-quick) and found some things missing in your repo.

It looks like you are missing a folder in the husky folder.
When I ran the `npx husky-init` command it provided me with this folder structure
<img width="329" alt="Screen Shot 2022-07-09 at 11 28 29 AM" src="https://user-images.githubusercontent.com/67210629/178118443-d2ef6697-3764-4e2a-a516-ee73da3a56ee.png">

I think that missing husky file is the problem.
I would rerun that `npx husky-init` command to make sure you have that folder in your repo. 
Then you can test your changes by poorly formatting the `Button.tsx` like I did earlier in this repo. 

Then stage and commit your changes. 
When everything is working correctly you should see this output and the Button.tsx file will be correctly formatted. 
<img width="762" alt="Screen Shot 2022-07-09 at 11 35 31 AM" src="https://user-images.githubusercontent.com/67210629/178118678-4b42386d-c832-4dc0-a318-a98694cc8a61.png">

Hope that helps! 👍

2022-07-09 20:20 UTC, a2937 commented
![Vs code screenshot](https://i.imgur.com/ozXIcdp.png)

I don't think the folder will actually ever be added because the git-ignore in the folder will keep it from being pushed. Secondly when I re-run the init; the contents of my pre-commit file get changed from ```npx pretty-quick --stage``` to ```npm test```. I think I chose the right format command. However I will be more than happy to look into again after a test push.

2022-07-09 20:23 UTC, a2937 commented
![PowerShell screenshot](https://imgur.com/HcDf09f) 

Another big issue I've ran into it is that I can't use Github Desktop to commit. Something about a command not found.

2022-07-09 20:25 UTC, a2937 commented
And here is the Github Desktop issue. 

![Github Desktop screenshot](https://i.imgur.com/XiWuXy3.png)

2022-07-09 23:17 UTC, jdwilkin4 approved these changes
LGTM! 👍

2022-07-09 23:17 UTC, merged

2022-07-09 23:21 UTC, jdwilkin4 commented
> I don't think the folder will actually ever be added because the git-ignore in the folder will keep it from being pushed.

That's true. Originally I thought it wasn't working on your end because you still had the unformatted `Button.tsx` file in your PR. But your latest push formatted that and everything looks good now. 👍