chore: standardize prefix language of questions
freeCodeCamp/Developer_Quiz_Site pull request #80
Opened 2022-07-02 21:53 UTC by erictleung

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #73

2022-07-04 20:44 UTC, jdwilkin4 requested changes
I think it looks good.
Just left a couple small comments 👍

2022-07-04 20:44 UTC, jdwilkin4 commented on src/data/full-quiz.ts
> +      "In JavaScript, in a switch statement, the __________________ case executes if none of the options are true.",
I think the wording can be clean up a bit

Proposed fix:
In a JavaScript switch statement, the __________________ case executes if none of the options are true.

2022-07-04 20:44 UTC, jdwilkin4 commented on src/data/full-quiz.ts
> +    Question: "In Flexbox, which one is NOT used with justify-content?",
I would change it to CSS Flexbox

2022-07-04 20:44 UTC, jdwilkin4 commented on src/data/full-quiz.ts
> +    Question: "In Flexbox, which one is NOT used with align-items?",
I would specify CSS Flexbox

2022-07-05 05:56 UTC, erictleung commented
Thanks for the feedback! I've found some more "flexbox" references that could be clarified as well and changed those too. Take a look when you have a chance.

2022-07-06 01:39 UTC, merged