adding a macrotask quiz question in javascript
freeCodeCamp/Developer_Quiz_Site pull request #820
Opened 2023-10-14 20:31 UTC by ht-l1

## Summary of changes

adding a macrotask quiz question in javascript

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #XXXXX

2023-10-14 21:34 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-14 21:34 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Question: "In JavaScript, which is an example of macrotask?",
```suggestion
    Question: "In JavaScript, which of the following is an example of a macrotask?",
```

2023-10-14 21:34 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Answer: "macrotask examples: setTimeout(), setInterval()",
```suggestion
    Answer: "setTimeout()",
```

2023-10-14 21:34 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +    Distractor2: "setTimeout()",
remember that distractors are for wrong answers only

```suggestion
    Distractor2: "split()",
```

2023-10-15 17:21 UTC, ht-l1 commented
thank you @jdwilkin4 ! Just committed all your changes :)

2023-10-15 22:05 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-10-15 22:06 UTC, merged