added some agile quiz questions
freeCodeCamp/Developer_Quiz_Site pull request #826
Opened 2023-10-15 17:09 UTC by SWASTI-SUNDAR

## Summary of changes
added some agile quiz questions

#103 
## Checklist

- [ ] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [ ] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [ ] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [ ] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [ ] I have provided a summary of my changes.

2023-10-15 22:11 UTC, jdwilkin4 reviewed
Before a review can be done, you will need to fix the formatting issue.
Please run `npm run fix-style`

2023-10-16 06:48 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-16 06:48 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +  },
this is a duplicate.
please remove

2023-10-16 06:48 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +  },
a similar question already exists in the file.
Please remove

2023-10-16 06:48 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +    Link: "https://www.freecodecamp.org/news/agile-software-development-handbook/#:~:text=Scrum%20Roles,on%20the%20most%20valuable%20features."
```suggestion
    Link: "https://www.freecodecamp.org/news/agile-software-development-handbook/#scrum-roles"
```

2023-10-16 06:48 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +  },
a similar question already exists in the file.
Please remove

2023-10-16 06:48 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
>    },
this is a duplicate question
please remove

2023-10-16 06:48 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +      "What are the major obstacles that are stopping your progress, and where do you need help?",
```suggestion
      "Deep discussions on frameworks and libraries",
```

2023-10-16 06:48 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +  },
a similar question already exists in the file.
Please remove

2023-10-16 13:18 UTC, SWASTI-SUNDAR commented
i have made all changes as required please review it @jdwilkin4

2023-10-16 14:28 UTC, jdwilkin4 requested changes

2023-10-16 14:28 UTC, jdwilkin4 commented on src/data/agile-quiz.ts
> +  },
@SWASTI-SUNDAR 

This duplicate is still here
It needs to be removed

2023-10-16 15:15 UTC, merged