Add question on Python list comprehensions
freeCodeCamp/Developer_Quiz_Site pull request #838
Opened 2023-10-16 16:24 UTC by khairalanam

## Summary of changes

This PR adds a new question to Python quiz on list comprehensions

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

2023-10-16 19:16 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-16 19:16 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "What will be the output for this code: print([i * i for i in range(10)]) ?",
```suggestion
      "What will be the output for this code: print([num * num for num in range(10)]) ?",
```

2023-10-17 02:46 UTC, khairalanam commented
I have implemented the changes. Thank you so much :)

2023-10-17 02:48 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-10-17 02:49 UTC, merged

2023-10-17 02:55 UTC, khairalanam commented
Thank you so much =D