Added Screen Reader application question to Accessibility-quiz.ts
freeCodeCamp/Developer_Quiz_Site pull request #855
Opened 2023-10-19 06:41 UTC by devesh-mishra13

## Summary of changes

question about licensed software of screen reader for windows.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

2023-10-19 15:36 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-19 15:36 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +    Question: "Which of the following screen reader is available as licensed software for windows?",
```suggestion
    Question: "Which of the following screen readers is available as licensed software for Windows?",
```

2023-10-20 05:24 UTC, devesh-mishra13 reviewed
JAWS question added.

2023-10-20 05:39 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-10-20 05:40 UTC, merged