A11y Quiz: HTML5 corresponding landmark question
freeCodeCamp/Developer_Quiz_Site pull request #878
Opened 2023-10-25 05:25 UTC by YuriDevAT

## Summary of changes

I added a question to the a11y quiz section regarding which one of the provided examples is not a corresponding role landmark.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [ ] I have provided a summary of my changes.

closes #XXXXX

2023-10-25 16:59 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-25 16:59 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +      "What is not one of the default landmark roles?",
```suggestion
      "Which of the following is NOT one of the default landmark roles?",
```

2023-10-25 16:59 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +      "form",
```suggestion
    Distractor3: "form",
```

2023-10-25 16:59 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +      "The <nav> element is an HTML element (semantic HTML). The corresponding default landmark role to <nav> is navigation, implemented as <div role='navigation'>",
```suggestion
      "The <nav> element is a semantic HTML element with a corresponding default landmark role of role='navigation'.",
```

2023-10-26 04:01 UTC, YuriDevAT commented
Thank you for taking time to improve my written English! 💟

2023-10-26 07:10 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-10-26 07:13 UTC, merged