A11y-Quiz: default landmark complementary counterpart
freeCodeCamp/Developer_Quiz_Site pull request #879
Opened 2023-10-25 05:38 UTC by YuriDevAT

## Summary of changes

For the a11y quiz I created a question regarding the counterpart of the default landmark complementary when using semantic HTML.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #XXXXX

2023-10-25 17:06 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-25 17:06 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +      "What is the semantic HTML counterpart to the default landmark complementary?",
```suggestion
      "Which of the following HTML elements uses the default landmark complementary?",
```

2023-10-25 17:06 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +      "This default landmark does not exist.",
```suggestion
    Distractor3: "div",
```

2023-10-25 17:06 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +      "If using semantic HTML, use the HTML tag <aside> element to define a complementary landmark.",
```suggestion
      "The semantic <aside> element uses the complementary landmark which is a supporting section of the document created to complement the main content.",
```

2023-10-26 04:04 UTC, YuriDevAT commented
Thanks for taking time to improve my written English 💟

2023-10-26 07:06 UTC, merged