Add JavaScript Question on Objects and Primitive values
freeCodeCamp/Developer_Quiz_Site pull request #881
Opened 2023-10-25 15:19 UTC by khairalanam

## Summary of changes

This PR adds a question to the JavaScript quiz on objects and primitive values.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

2023-10-25 17:33 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-25 17:33 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "Which one of the following values is considered as a primitive value?",
```suggestion
      "Which one of the following is considered a primitive value in JavaScript?",
```

2023-10-25 17:33 UTC, jdwilkin4 commented on src/data/javascript-quiz.ts
> +      "There are 7 primitive data types in JavaScript; namely string, number, boolean, null, undefined, symbol, and bigint. Everything else is a JavaScript object including arrays, sets, functions, d
```suggestion
      "There are 7 primitive data types in JavaScript: strings, numbers, booleans, null, undefined, Symbol, and BigInt. Everything else is a JavaScript object including arrays, sets, functions, dates, etc.",
```

2023-10-26 04:21 UTC, khairalanam commented
I have implemented the changes.

2023-10-26 07:04 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-10-26 07:04 UTC, merged

2023-10-26 07:05 UTC, khairalanam commented
Thank you!