Add Python question on Dunder methods
freeCodeCamp/Developer_Quiz_Site pull request #888
Opened 2023-10-26 11:11 UTC by khairalanam

## Summary of changes

The PR adds a question in the Python quiz about dunder methods.

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

2023-10-26 18:13 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-26 18:13 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "Which of the following dunder methods allows you to do the expression x + y, where x and y are two objects of the same class?",
```suggestion
      "In Python, which of the following dunder methods defines the behavior of the addition operator + for objects of a class?",
```

2023-10-26 18:13 UTC, jdwilkin4 commented on src/data/python-quiz.ts
> +      "Dunder methods (Double underscore) are special methods reserved in Python which affect's the behaviour of the object and the interaction of the object with other objects.",
```suggestion
      "Dunder methods (Double underscore) are special methods reserved in Python which affect's the behavior of the object and the interaction of the object with other objects.",
```

2023-10-27 02:10 UTC, khairalanam commented
I have implemented the changes.

2023-10-27 02:45 UTC, jdwilkin4 approved these changes
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-10-27 02:46 UTC, merged

2023-10-27 03:50 UTC, khairalanam commented
Thank you!