add LLD ques
freeCodeCamp/Developer_Quiz_Site pull request #889
Opened 2023-10-26 13:57 UTC by babitarit

## Summary of changes

## Checklist

- [ ] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [ ] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [ ] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [ ] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [ ] I have provided a summary of my changes.

closes #XXXXX

2023-10-26 18:16 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-26 18:16 UTC, jdwilkin4 commented on src/data/general-cs-quiz.ts
> +    Question: "What is load Balancing in LLD(Low Level Design)?",
```suggestion
    Question: "What is load balancing in LLD(Low Level Design)?",
```

2023-10-27 04:25 UTC, babitarit commented
@jdwilkin4 i had done the required changes please review it

2023-10-27 05:44 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-10-27 05:45 UTC, merged