Add beginner friendly accessibility questions
freeCodeCamp/Developer_Quiz_Site pull request #904
Opened 2023-10-28 19:18 UTC by THEFZNKHAN

## Summary of changes

Add six more questions in the beginner-friendly accessibility questions.
Mentioned in issue #899

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

closes #XXXXX

2023-10-28 22:55 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2023-10-28 22:55 UTC, jdwilkin4 commented on src/data/accessibility-quiz.ts
> +    Question: "What is the role of labels in accessibility?",
```suggestion
    Question: "What is the role of a label in accessibility?",
```

2023-10-29 07:31 UTC, THEFZNKHAN commented
I change the "labels" to "label"
If any other problem than tell me 😊

2023-10-29 07:36 UTC, THEFZNKHAN commented
Sorry for too many commits 
But I do typos by mistake.

2023-10-29 17:39 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2023-10-29 17:40 UTC, merged