refactor: make App to use routes instead of state
freeCodeCamp/Developer_Quiz_Site pull request #934
Opened 2024-01-08 17:39 UTC by shootermv

## Summary of changes

## Checklist

- [x] I have read and followed the [contribution guidelines](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md).
- [x] I have read through the [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md) and agree to abide by the rules.
- [x] This PR is for one of the available issues and is not a PR for an issue already assigned to someone else.
- [x] My PR title has a short descriptive name so the maintainers can get an idea of what the PR is about.
- [x] I have provided a summary of my changes.

related to #933

2024-01-09 06:51 UTC, jdwilkin4 requested changes
Was playing around with it locally and things were working well on my end. 

I agree with the earlier comments about the accessibility issues surrounding the use of the button.

2024-01-09 06:51 UTC, jdwilkin4 commented on src/components/HeroSection.tsx
> +          <NavLink to="/quizes">
spelling error here 

```suggestion
          <NavLink to="/quizzes">
```

2024-01-09 06:51 UTC, jdwilkin4 commented on src/components/WelcomePage.tsx
> +            <NavLink to="/quizes">
```suggestion
            <NavLink to="/quizzes">
```

2024-01-09 07:58 UTC, shootermv commented on src/components/HeroSection.tsx
> +          <NavLink to="/quizes">
chnaged  quizes -> quizzes

2024-01-09 09:35 UTC, shootermv commented on src/components/HeroSection.tsx
> +          </NavLink>
created link button component, which is styled like a button

2024-01-09 15:05 UTC, shootermv commented on src/components/LinkButton.tsx
> +const LinkButton: React.FC<LinkButtonProps> = ({ to, children, isLarge }) => {
had exactly same feeling! ButtonLink is better

2024-01-09 20:12 UTC, jdwilkin4 requested changes
Spotted a couple of cleanup items

2024-01-09 20:12 UTC, jdwilkin4 commented on src/components/WelcomePage.tsx
>  import Button from "./Button";
If this is no longer being used then it can be removed from the file here

2024-01-09 20:12 UTC, jdwilkin4 commented on src/components/WelcomePage.tsx
> +import { NavLink } from "react-router-dom";
same issue here.
If NavLink is not being used here, then this import is not necessary

2024-01-10 04:01 UTC, jdwilkin4 approved these changes
Looks good to merge in 👍

2024-01-10 04:01 UTC, merged